name: All Scans

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  All-Scans:
  runs-on: ubuntu-latest
  permissions:
  actions: read
  contents: read
  security-events: write

  steps:
    -name: Checkout Source Code
    uses: actions/checkout@v4
  
    -name: Setup Java
    uses: actions/setup-java@v4
    with:
      java-version: 21
      distribution: "temurin"

    -name: Echo
    run: echo "Testing workflow build complete"

    

