name: All Scans

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  All-Scans:
  runs-on: ubuntu-latest
  permissions:
  actions: read
  contents: read
  security-events: write

  steps:
    -name: Checkout Source Code
    uses: actions/checkout@v4
  
    -name: Setup Java
    uses: actions/setup-java@v4
    with:
      java-version: 21
      distribution: "temurin"

### SNYK SCAN and Results Upload to GitHub Code Scanning ###

#  -name: Example workflow for Maven using Snyk
#   uses: snyk/actions/maven@master
#   continue-on-error: true # To make sure that SARIF upload gets called
#   env:
##     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#   with:
#     args: --sarif-file-output=snyk.sarif
 
 # -name: Upload result to GitHub Code Scanning
 #  uses: github/codeql-action/upload-sarif@v2
 #  with:
 #    sarif_file: snyk.sarif

### Debricked Scan ###

  -name: Debricked scan
  steps:
    - uses: actions/checkout@v4
    - uses: debricked/actions/cache@v4
    - uses: debricked/actions/resolve-non-docker@v4
    - uses: debricked/actions/scan-non-docker@v4
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}


