name: FOD SAST Scan

on: 
  push:
    branches: ["master", "na_develop"]

jobs:
  Temporary_test_workflow:    
    runs-on: ubuntu-latest
    name: Executing Echo Test
    steps:
      - name: Echoing One
        run: echo "Echo 1"
      - name: Try to fail
        run: exit 1
      - name: Print message if we do not fail
        run: echo Should not get here
