name: Simple Workflow

on: 
  workflow_dispatch:
  # push:
  #   branches: ["na_develop"]

jobs:
  Temporary_test_workflow:    
    runs-on: ubuntu-latest
    name: Executing Echo Test
    steps:
      - name: Echoing One
        run: echo "Echo 1"
